import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { ToastContainer } from "react-toastify";
import { ProductProvider } from "./Context/useContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "The Chicken World",
  description: "Generated by Mohammad Hasib",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html
        lang="en"
        data-theme="light"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body>
          <Nav></Nav>
          <ProductProvider>{children}</ProductProvider>
        </body>
      </html>
      <ToastContainer></ToastContainer>
    </>
  );
}
